### ISSUE TITLE
JDK 8 updated

### ISSUE THREAD

**Issue by scottconnerly** [MihaiBogdanEugen/docker-debian-oracle-java#19]
8u162-b12 is no longer available.
Please update to 8u172-b11.

JAVA_UPDATE=172
JAVA_BUILD=11
JAVA_PATH=a58eab1ec242421181065cdc37240b08

Please verify before including these:
JAVA_SHA256_SUM=f08f25aec2bdc86138ccba8fd5b904451e3afa1d24a88c85f28c2d84bfd45bad
JCE_SHA256_SUM=f3020a3922efd6626c2fff45695d527f34a8020e938a49292561f18ad1320b59

Also, FYI to others, on OSX you can use `shasum -a 256` in lieu of `sha256sum` to generate/check sum's.

**Comment by MihaiBogdanEugen** [comment]
I've just solved this, in roughly one hour the images should be updated on Docker Hub as well.
